import type { Metadata } from "next";
import { Poppins } from "next/font/google";



import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-providers";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";


const poppins = Poppins({
  subsets:["latin"],
  weight:["100","200","300","400","500","600","700","800","900"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
      <SessionProvider session={session}>
    <html lang="en">
    
      <body
        className={`${poppins.className} antialiased `}
      >
          <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
       <Toaster />
       {children}
    </ThemeProvider>
       
      </body>
    </html>
    </SessionProvider>
  );
}
